INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('MERCEDES', 'S500', '5', '50000', 2004);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('FORD', 'FOCUS', '5', '10000', 2010);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('FORD', 'FUSION', '5', '50000', 2004);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('NISSAN', 'ROGUE', '5', '20000', 2008);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('NISSAN', 'PATHFINDER', '7', '45000', 2012);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('NISSAN', 'ALTIMA', '5', '5000', 2015);
INSERT INTO VEHICLE (VEHICLE_TYPE, VEHICLE_MODEL, NUMBER_OF_PASSENGERS, NUMBER_OF_KILOMETERS, PRODUCTION_YEAR) VALUES ('MERCEDES', 'CLA250', '5', '4000', 2012);

INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('JOHN', 'DOLL', 'JOHNDOLL@GMAIL.COM', 'UNITED STATES', '12 BROOKLYN BRIDGE PARK', 'NY', '1-(111)111-1111');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('SOPHIA', 'THOMPSON', 'SOPHIATHOMPSON@GMAIL.COM', 'UNITED STATES', '1418 LEERY CV', 'TN', '2-(222)222-2222');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('DANNY', 'KHAN', 'DANNYKHAN@GMAIL.COM', 'UNITED STATES', '8814 BAY PKWY', 'NY', '1-(333)333-3333');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('MICHELLE', 'SABOUR', 'MICHELLESABOUR@GMAIL.COM', 'UNITED STATES', '123 MICHIGAN AVE', 'MI', '1-(444)444-4444');
INSERT INTO CLIENT (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES ('DONNY', 'WALDORF', 'DONNYWALDORF@GMAIL.COM', 'UNITED STATES', '1288 BROOKLYN BRIDGE PARK', 'NY', '1-(555)555-5555');

INSERT INTO RESERVATION (VEHICLE_ID, CLIENT_ID, RESERVATION_DATE) VALUES ((SELECT VEHICLE_ID FROM VEHICLE WHERE VEHICLE_MODEL = 'S500'), (SELECT CLIENT_ID FROM CLIENT WHERE LAST_NAME = 'DOLL'), '2019-06-12');